/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carbonfootprintcalc;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author jordancarthy
 */
public class CarbonGUI extends javax.swing.JFrame {
// declare my variables
    ArrayList<CarbonFootPrint> footPrints;
    double value;
    double electricBill;
    double gasBill;
    double oilBill;
    double flightLessFour;
    double flightMoreFour;
    double carYearlyMileage;

    /**
     * Creates new form CarbonFootCalc
     */
    public CarbonGUI() {
        initComponents();
        footPrints = new ArrayList<>();
        errorLBL.setVisible(false);
        carbonTabPane.setSelectedComponent(introPane);
        displayPanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carbonButtonGroup = new javax.swing.ButtonGroup();
        hiddenTabPanel = new javax.swing.JPanel();
        billsRB = new javax.swing.JRadioButton();
        transportRB = new javax.swing.JRadioButton();
        recyclingRB = new javax.swing.JRadioButton();
        carbonTabPane = new javax.swing.JTabbedPane();
        transportPane = new javax.swing.JLayeredPane();
        flightsLessLBL = new javax.swing.JLabel();
        flightsMoreLBL = new javax.swing.JLabel();
        carYearlyLBL = new javax.swing.JLabel();
        carYearlyTF = new javax.swing.JTextField();
        flightsLessTF = new javax.swing.JTextField();
        flightsMoreTF = new javax.swing.JTextField();
        recyclePane = new javax.swing.JPanel();
        aluminumCB = new javax.swing.JCheckBox();
        newspaperCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        billsPane = new javax.swing.JLayeredPane();
        oilTF = new javax.swing.JTextField();
        gasBIllLBL = new javax.swing.JLabel();
        gasTF = new javax.swing.JTextField();
        electricTF = new javax.swing.JTextField();
        oilBillLBL = new javax.swing.JLabel();
        electricBillLBL = new javax.swing.JLabel();
        introPane = new javax.swing.JPanel();
        introFirstTextLBL = new javax.swing.JLabel();
        introSecondTextLBL = new javax.swing.JLabel();
        introThirdTextLBL = new javax.swing.JLabel();
        errorLBL = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        loadBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        addBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hiddenTabPanel.setLayout(new javax.swing.OverlayLayout(hiddenTabPanel));
        getContentPane().add(hiddenTabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 44, 270));

        carbonButtonGroup.add(billsRB);
        billsRB.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        billsRB.setText("Bills");
        billsRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                billsRBItemStateChanged(evt);
            }
        });
        billsRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsRBActionPerformed(evt);
            }
        });
        getContentPane().add(billsRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        carbonButtonGroup.add(transportRB);
        transportRB.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        transportRB.setText("Transport");
        transportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportRBActionPerformed(evt);
            }
        });
        getContentPane().add(transportRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 20));

        carbonButtonGroup.add(recyclingRB);
        recyclingRB.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        recyclingRB.setText("Recycling");
        recyclingRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recyclingRBActionPerformed(evt);
            }
        });
        getContentPane().add(recyclingRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 100, 20));

        carbonTabPane.setBackground(new java.awt.Color(65, 65, 65));
        carbonTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        transportPane.setFont(new java.awt.Font("American Typewriter", 0, 12)); // NOI18N

        flightsLessLBL.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        flightsLessLBL.setText("Flights that were four hours or more :");

        flightsMoreLBL.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        flightsMoreLBL.setText("Flights that were less than four hours :");

        carYearlyLBL.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        carYearlyLBL.setText("Your cars yearly mileage :");

        transportPane.setLayer(flightsLessLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        transportPane.setLayer(flightsMoreLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        transportPane.setLayer(carYearlyLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        transportPane.setLayer(carYearlyTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        transportPane.setLayer(flightsLessTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        transportPane.setLayer(flightsMoreTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout transportPaneLayout = new javax.swing.GroupLayout(transportPane);
        transportPane.setLayout(transportPaneLayout);
        transportPaneLayout.setHorizontalGroup(
            transportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transportPaneLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(transportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carYearlyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carYearlyLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightsLessTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightsLessLBL)
                    .addComponent(flightsMoreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightsMoreLBL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transportPaneLayout.setVerticalGroup(
            transportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transportPaneLayout.createSequentialGroup()
                .addComponent(flightsLessLBL)
                .addGap(3, 3, 3)
                .addComponent(flightsMoreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(flightsMoreLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightsLessTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carYearlyLBL)
                .addGap(3, 3, 3)
                .addComponent(carYearlyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        carbonTabPane.addTab("transportTab", transportPane);

        recyclePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aluminumCB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        aluminumCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aluminumCBActionPerformed(evt);
            }
        });
        recyclePane.add(aluminumCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        newspaperCB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        newspaperCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newspaperCBActionPerformed(evt);
            }
        });
        recyclePane.add(newspaperCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        jLabel1.setText("Aluminum");
        recyclePane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        jLabel2.setText("Newspaper");
        recyclePane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel3.setText("Please Tick The Following Boxes ");
        recyclePane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 260, 20));

        jLabel4.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jLabel4.setText("If you Recycle These Materials :");
        recyclePane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 230, -1));

        carbonTabPane.addTab("recycleTab", recyclePane);

        billsPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        billsPane.add(oilTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 89, -1));

        gasBIllLBL.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        gasBIllLBL.setText("Gas Bill");
        billsPane.add(gasBIllLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, -1));
        billsPane.add(gasTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 88, -1));

        electricTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricTFActionPerformed(evt);
            }
        });
        billsPane.add(electricTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 88, -1));

        oilBillLBL.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        oilBillLBL.setText("Oil bill");
        billsPane.add(oilBillLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 60, -1));

        electricBillLBL.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        electricBillLBL.setText("Electric bill");
        billsPane.add(electricBillLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, -1));

        carbonTabPane.addTab("billsTab", billsPane);

        introFirstTextLBL.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        introFirstTextLBL.setText("This is the Carbon Footprint Calculator");

        introSecondTextLBL.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        introSecondTextLBL.setText("To begin please select one of the radio buttons above");

        introThirdTextLBL.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        introThirdTextLBL.setText("p.s don't enter any letters when entering values ....");

        javax.swing.GroupLayout introPaneLayout = new javax.swing.GroupLayout(introPane);
        introPane.setLayout(introPaneLayout);
        introPaneLayout.setHorizontalGroup(
            introPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introPaneLayout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(introPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(introThirdTextLBL)
                    .addGroup(introPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(introFirstTextLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(introSecondTextLBL))))
        );
        introPaneLayout.setVerticalGroup(
            introPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introPaneLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(introFirstTextLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(introSecondTextLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(introThirdTextLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        carbonTabPane.addTab("tab4", introPane);

        getContentPane().add(carbonTabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 70, 470, 170));

        errorLBL.setText("PLEASE ENTER A NUMBER !!!!");
        getContentPane().add(errorLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, -1));

        loadBTN.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        loadBTN.setText("Load");
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane2.setViewportView(displayTA);

        addBTN.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        saveBTN.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        displayBTN.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(addBTN)
                        .addGap(18, 18, 18)
                        .addComponent(loadBTN)
                        .addGap(18, 18, 18)
                        .addComponent(saveBTN))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(displayBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loadBTN)
                        .addComponent(addBTN))
                    .addComponent(saveBTN))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(displayBTN)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(displayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    Created a show display function to ensure that the display of textarea for file reading is only shown when a radio button is selected
    public void showDisplay(){
        displayPanel.setVisible(true);
    }
    
    
    private void electricTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_electricTFActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        try{
        if (billsRB.isSelected()) {
            electricBill = Double.parseDouble(electricTF.getText());
            gasBill = Double.parseDouble(gasTF.getText());
            oilBill = Double.parseDouble(oilTF.getText());

            CarbonFootPrint carbonBills = new CarbonBills("Bills", value, electricBill, gasBill, oilBill);
            carbonBills.computeCarbonFoot();
            footPrints.add(carbonBills);
            displayTA.append("\n Monthly bills Added");
            errorLBL.setVisible(false);
            clearFields();
        } 
        if (recyclingRB.isSelected()) {  // addBTN logic for recycling radio button or equivalent
            // Get the checkbox states to determine if aluminum or newspaper is being recycled
            displayPanel.setVisible(true);
            boolean isAluminumRecycled = false;
            boolean isNewspaperRecycled = false;
            if (aluminumCB.isSelected()) {
                isAluminumRecycled = true;
            }
            if (newspaperCB.isSelected()) {
                isNewspaperRecycled = true;
            }

            CarbonRecycle carbonRecycle = new CarbonRecycle("Recycling", value, isAluminumRecycled, isNewspaperRecycled);
            carbonRecycle.computeCarbonFoot();

            footPrints.add(carbonRecycle);
            displayTA.append("\nRecycling added");
            errorLBL.setVisible(false);
            clearFields();       
    }//GEN-LAST:event_addBTNActionPerformed
         if(transportRB.isSelected()){
            flightLessFour = Double.parseDouble(flightsLessTF.getText());
            flightMoreFour = Double.parseDouble(flightsMoreTF.getText());
            carYearlyMileage = Double.parseDouble(carYearlyTF.getText());

            CarbonFootPrint carbonTransport = new CarbonTransport("Transport", value, flightLessFour, flightMoreFour,  carYearlyMileage);
            carbonTransport.computeCarbonFoot();
            footPrints.add(carbonTransport);
            displayTA.append("\nTransport added");
            errorLBL.setVisible(false);
            clearFields();
            
        }
        } catch(NumberFormatException e){
            System.out.println("Error : " + e);
            errorLBL.setVisible(true);
            clearFields();
        }
    }
       
    
    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        try {
            f = new File("footprints.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(footPrints);
            oStream.close();
            displayTA.append("\nSuccesfully saved file");
        } catch (IOException e) {
            System.out.println("I/O e :" + e);
        }
    }//GEN-LAST:event_saveBTNActionPerformed
     private void loadFile() {
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        try {
            f = new File("footprints.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            footPrints = (ArrayList<CarbonFootPrint>) oStream.readObject();
            oStream.close();

        } catch (IOException | ClassNotFoundException e) {
            System.out.println("File input" + e);
        }

    }
//     Clear Fields method
    private void clearFields() {
        oilTF.setText("");
        electricTF.setText("");
        gasTF.setText("");
        flightsLessTF.setText("");
        flightsMoreTF.setText("");
        carYearlyTF.setText("");
        newspaperCB.setSelected(false);
         aluminumCB.setSelected(false);
         
    }
    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        // TODO add your handling code here:
        loadFile();
    }//GEN-LAST:event_loadBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        for (CarbonFootPrint print : footPrints) {
            displayTA.append("\n" + print.toString());
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void billsRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsRBActionPerformed
        // TODO add your handling code here:
        if (billsRB.isSelected()) {
            carbonTabPane.setSelectedComponent(billsPane);
            showDisplay();
        } else {
            billsPane.setVisible(false);
        }

    }//GEN-LAST:event_billsRBActionPerformed

    private void billsRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_billsRBItemStateChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_billsRBItemStateChanged

    private void transportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportRBActionPerformed
        // TODO add your handling code here:
        if (transportRB.isSelected()) {
            carbonTabPane.setSelectedComponent(transportPane);
            showDisplay();
        } else {
            transportPane.setVisible(false);
        }
    }//GEN-LAST:event_transportRBActionPerformed

    private void newspaperCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newspaperCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newspaperCBActionPerformed

    private void recyclingRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recyclingRBActionPerformed
        // TODO add your handling code here:
        if (recyclingRB.isSelected()) {
            carbonTabPane.setSelectedComponent(recyclePane);
            showDisplay();
        } else {
            billsPane.setVisible(false);
        }
    }//GEN-LAST:event_recyclingRBActionPerformed

    private void aluminumCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aluminumCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aluminumCBActionPerformed
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarbonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarbonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JCheckBox aluminumCB;
    private javax.swing.JLayeredPane billsPane;
    private javax.swing.JRadioButton billsRB;
    private javax.swing.JLabel carYearlyLBL;
    private javax.swing.JTextField carYearlyTF;
    private javax.swing.ButtonGroup carbonButtonGroup;
    private javax.swing.JTabbedPane carbonTabPane;
    private javax.swing.JButton displayBTN;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JLabel electricBillLBL;
    private javax.swing.JTextField electricTF;
    private javax.swing.JLabel errorLBL;
    private javax.swing.JLabel flightsLessLBL;
    private javax.swing.JTextField flightsLessTF;
    private javax.swing.JLabel flightsMoreLBL;
    private javax.swing.JTextField flightsMoreTF;
    private javax.swing.JLabel gasBIllLBL;
    private javax.swing.JTextField gasTF;
    private javax.swing.JPanel hiddenTabPanel;
    private javax.swing.JLabel introFirstTextLBL;
    private javax.swing.JPanel introPane;
    private javax.swing.JLabel introSecondTextLBL;
    private javax.swing.JLabel introThirdTextLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadBTN;
    private javax.swing.JCheckBox newspaperCB;
    private javax.swing.JLabel oilBillLBL;
    private javax.swing.JTextField oilTF;
    private javax.swing.JPanel recyclePane;
    private javax.swing.JRadioButton recyclingRB;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLayeredPane transportPane;
    private javax.swing.JRadioButton transportRB;
    // End of variables declaration//GEN-END:variables
}
